# Site settings
title: Jack Mackenzie Pointer
email: simon.stanley87@gmail.com
description: Jack Mackenzie Pointer, dancer, choreography and visionary.
url: "http://simonstanley.github.io/jack" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
