# Site settings
url: https://simonstanley.github.io/career-breaking
title: Career Breaking
email: simon.stanley87@gmail.com
img_dir: /assets/img

# Build settings
markdown: kramdown
sass:
    sass_dir: /assets/css
